-- created Database
create database PROJECT;
-- using Database
USE PROJECT;


-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    cat_name VARCHAR(255)
);


-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);


-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);





-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    CONSTRAINT fk_products_supplier
        FOREIGN KEY (sup_id)
        REFERENCES supplier(sup_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_products_categories
        FOREIGN KEY (cat_id)
        REFERENCES categories(cat_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    CONSTRAINT fk_orders_customers
        FOREIGN KEY (cust_id)
        REFERENCES customers(cust_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_orders_employees
        FOREIGN KEY (emp_id)
        REFERENCES employees(emp_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_det_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    CONSTRAINT fk_orderdetails_orders
        FOREIGN KEY (ord_id)
        REFERENCES orders(ord_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_orderdetails_products
        FOREIGN KEY (prod_id)
        REFERENCES products(prod_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

describe categories;
describe customers;
describe employees;
describe order_details;
describe orders;
describe products;
describe supplier;




-- Analysis Questions

-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.

-- 1.1 How many unique customers have placed orders?

SELECT COUNT(DISTINCT(cust_id)) AS "Unique Customer"
FROM orders;


-- 1.2 which customers have placed the highest number of orders?
SELECT c.cust_id,
       c.cust_name,
       COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC limit 1;


-- 1.3 What is the total and average purchase value per customer?
SELECT c.cust_id,
       c.cust_name,
       SUM(od.total_price) AS total_spent,
       AVG(od.total_price) AS avg_spent
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name;


-- 1.4 Who are the top 5 customers by total purchase amount?
SELECT c.cust_id,
       c.cust_name,
       SUM(od.total_price) AS total_revenue
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_revenue DESC
LIMIT 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

-- 2.1 How many products exist in each category?
SELECT cat.cat_name,
       COUNT(p.prod_id) AS total_products
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name 
order by total_products desc;


-- 2.2 What is the average price of products by category?
SELECT cat.cat_name,
       AVG(p.price) AS avg_price
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name
order by avg_price desc ;




-- 2.3 Which products have the highest total sales volume (by quantity)?
SELECT p.prod_name,
       SUM(od.quantity) AS total_quantity_sold
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_quantity_sold DESC limit 1;


-- 2.4 What is the total revenue generated by each product?
SELECT p.prod_name,
       SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_revenue DESC;



-- 2.5 How do product sales vary by category and supplier?
SELECT cat.cat_name,
       s.sup_name,
       SUM(od.total_price) AS total_sales
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories cat ON p.cat_id = cat.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY cat.cat_name, s.sup_name
ORDER BY total_sales DESC;



-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.


-- 3.1 How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;


-- 3.2 What is the average value per order?
 SELECT AVG(order_total) AS avg_order_value
FROM (
    SELECT ord_id,
           SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) t;


-- 3.3 On which dates were the most orders placed?
SELECT order_date,
       COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC limit 1;


-- 3.4 What are the monthly trends in order volume and revenue?
SELECT 
month(STR_TO_DATE(order_date, '%m/%d/%Y')) AS ord_month,
COUNT(DISTINCT o.ord_id) AS ord_volume,
SUM(od.total_price) AS total_revenue
FROM orders o
INNER JOIN order_details od
ON o.ord_id= od.ord_id
GROUP BY ord_month
ORDER BY ord_month;


-- 3.5 How do order patterns vary across weekdays and weekends?
SELECT 
	 weekday((STR_TO_DATE(order_date, '%m/%d/%Y')))AS days,
	dayname((STR_TO_DATE(order_date, '%m/%d/%Y')))AS weekdays,
    COUNT(ord_id) AS total_orders
FROM orders 
GROUP BY days,weekdays
order by days,weekdays asc;




-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.

-- 4.1 How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;


-- 4.2 Which supplier provides the most products?
SELECT s.sup_name,
       COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name
ORDER BY total_products DESC limit 1;




-- 4.3 What is the average price of products from each supplier?
SELECT s.sup_name,
       AVG(p.price) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name;



--  4.4 Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.sup_name,
       SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_name
ORDER BY total_revenue DESC limit 1;



-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.

-- 5.1 How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) As No_of_employee_pro
FROM orders;


-- 5.2 Which employees have handled the most orders?
SELECT e.emp_name,
       COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_name
ORDER BY total_orders DESC limit 1;



-- 5.3 What is the total sales value processed by each employee?
SELECT e.emp_name,
	   SUM(od.quantity) as totalquantity,
       SUM(od.total_price) AS total_revenue
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_name
ORDER BY total_revenue DESC;





-- 5.4 What is the average order value handled per employee?
SELECT e.emp_name,
       AVG(order_total) AS avg_order_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN (
    SELECT ord_id,
           SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) t ON o.ord_id = t.ord_id
GROUP BY e.emp_name 
order by avg_order_value desc ;



-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.



-- 6.1 What is the relationship between quantity ordered and total price?
SELECT quantity,
       AVG(total_price) AS avg_total_price
FROM order_details
GROUP BY quantity
ORDER BY quantity;


-- 6.2 What is the average quantity ordered per product?
SELECT p.prod_name,
       AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name 
order by avg_quantity desc;



-- 6.3 How does the unit price vary across products and orders?

SELECT p.prod_id,p.prod_name,od.each_price AS unit_price,COUNT(od.ord_id) AS times_ordered
FROM products p
INNER JOIN order_details od
    ON p.prod_id = od.prod_id
GROUP BY p.prod_id,od.each_price
ORDER BY p.prod_id,od.each_price; 
    
