USE PROJECT;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);
select * from supplier;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    cat_name VARCHAR(255)
);

select * from categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);
select * from employees;


-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);


select * from customers;


-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    CONSTRAINT fk_products_supplier
        FOREIGN KEY (sup_id)
        REFERENCES supplier(sup_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_products_categories
        FOREIGN KEY (cat_id)
        REFERENCES categories(cat_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
select * from products;


-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    CONSTRAINT fk_orders_customers
        FOREIGN KEY (cust_id)
        REFERENCES customers(cust_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_orders_employees
        FOREIGN KEY (emp_id)
        REFERENCES employees(emp_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

select * from orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_det_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    CONSTRAINT fk_orderdetails_orders
        FOREIGN KEY (ord_id)
        REFERENCES orders(ord_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_orderdetails_products
        FOREIGN KEY (prod_id)
        REFERENCES products(prod_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- 1. Customer Insights
-- 1 How many unique customers have placed orders?
SELECT count(DISTINCT(cust_id))AS unique_customers
FROM orders;

-- 2 Which customers have placed the highest number of orders?

SELECT c.cust_name 
	AS "Customer Name",count(o.cust_id) AS "Total Orders"  
FROM customers c 
LEFT JOIN orders o 
	ON c.cust_id=o.cust_id
GROUP BY 1 
ORDER BY 2 
DESC LIMIT 1;


-- 3 What is the total and average purchase value per customer? 

SELECT c.cust_name as " NAME ",sum(total_price) as "TOTAL PRICE",avg(total_price) as "AVERAGE"
FROM customers c 
left JOIN orders o 
	ON c.cust_id=o.cust_id
INNER JOIN order_details od 
on od.ord_id =o.ord_id
group by 1 order by 2,3;

-- 4 Who are the top 5 customers by total purchase amount?

SELECT c.cust_name as " NAME ",sum(total_price) as "TOTAL PRICE"
FROM customers c 
left JOIN orders o 
	ON c.cust_id=o.cust_id
INNER JOIN order_details od 
on od.ord_id =o.ord_id
group by 1 order by 2 desc limit 5;

########################################################################################################################################

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.


-- 1. How many products exist in each category?
SELECT c.cat_name AS "CATEGORY",count(p.prod_name) AS "COUNT" FROM categories c 
LEFT JOIN products p ON
c.cat_id=p.cat_id
GROUP BY 1 ORDER BY 2 ;


-- 2. What is the average price of products by category?
SELECT c.cat_name AS "CATEGORY",avg(p.price) AS "AVERAGE" ,sum(p.price) AS "TOTAL" FROM categories c 
left JOIN products p ON
c.cat_id=p.cat_id
GROUP BY 1 ORDER BY 2,3 desc ;

-- 3. Which products have the highest total sales volume (by quantity)?


SELECT p.prod_name,o.each_price,sum(o.quantity) as quantity,sum(o.total_price)as Total
from products p  join order_details o 
on p.prod_id=o.prod_id
group by 1,2 order by Total desc limit 1;

-- 4. What is the total revenue generated by each product?

SELECT p.prod_name,o.each_price,sum(o.quantity) as quantity,sum(o.total_price)as "Total Revenue"
from products p  join order_details o 
on p.prod_id=o.prod_id
group by 1,2 order by "Total Revenue" desc ;


-- 5.How do product sales vary by category and supplier?

select * from supplier,products,categories,order_details;

select sup_name as "NAME",cat_name as "CATEGORIES",sum(total_price) as "SALES",sum(od.quantity) as "QUANTITY" from supplier s 
inner join 
products p on s.sup_id=p.sup_id
inner join 
categories c on c.cat_id=p.cat_id
inner join 
order_details od  on od.prod_id=p.prod_id
group by name,CATEGORIES order by name ;
#################################################################################################################################################################################

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.

select * from orders,order_details;

select month(STR_TO_DATE(o.order_date, '%m/%d/%Y'))as Months,sum(od.quantity) as "quantity", sum(od.total_price) as Revenu from orders o 
inner join 
order_details od on o.ord_id =od.ord_id
group by months 
order by 3 desc;




-- How many orders have been placed in total?

select count(*) as "ORDER PLACED" from order_details;


-- What is the average value per order?
select count(*) as "TOTAL_ORDERS" , avg(each_price) as "AVERAGE PER ORDERS" from order_details;



-- On which dates were the most orders placed?




select date(STR_TO_DATE(order_date, '%m/%d/%Y'))as dates,count(*) as orders_ from orders
group by dates order by 2 desc;


-- What are the monthly trends in order volume and revenue?
select * from orders;
select * from order_details;

with cte as(
select  month(STR_TO_DATE(o.order_date, '%m/%d/%Y'))as Months,sum(od.quantity) as Volumn ,sum(od.total_price) as revenue
from orders o
join order_details od on o.ord_id = od.ord_id
group by 1
),
cte2 as(
select *,lag(revenue) over (order by months) as last_month_revenue from cte c)
select *,(revenue-last_month_revenue) as Difference from cte2;

-- How do order patterns vary across weekdays and weekends?


select  dayname(STR_TO_DATE(o.order_date, '%m/%d/%Y'))as weekday,sum(od.quantity) as Volumn ,sum(od.total_price) as revenue
from orders o
left join order_details od on o.ord_id = od.ord_id
group by 1;

#######################################################################################################################################################################





-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- How many suppliers are there in the database?

select count(*) as "NUMBER OF SUPPLIERS" from supplier;

-- Which supplier provides the most products?

select * from supplier,products;

select sup_name,prod_name from supplier s 
 join products p on 
s.sup_id=p.sup_id;

select sup_name,count(prod_name) as Products from supplier s 
 join products p on 
s.sup_id=p.sup_id
group by 1 order by 2 desc ;




-- What is the average price of products from each supplier?


-- Which suppliers contribute the most to total product sales (by revenue)?

#######################################################################################################################################################################

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- How many employees have processed orders?

select * from employees,orders;

-- Which employees have handled the most orders?


-- What is the total sales value processed by each employee?


-- What is the average order value handled per employee?

#######################################################################################################################################################################
-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- What is the relationship between quantity ordered and total price?


-- What is the average quantity ordered per product?


-- How does the unit price vary across products and orders?




